services:
  loki:
    image: grafana/loki:latest
    container_name: pace-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pace-auth-api
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://mongo:27017/user-auth
      NODE_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      loki:
        condition: service_started
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: pace-mongo
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: pace-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=pace_user
      - GF_SECURITY_ADMIN_PASSWORD=pace_pass
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  mongo_data: